### PR TITLE
change navigation bar and them of website and fix bug

### PR DESCRIPTION
**Pull request by Aditya21neve**
Change the design of website. work on the color combination and fixed buges

### CODE REVIEW

**Comment by Deadshot0x7** [comment]
Buddy can fix the toggle key?

**Comment by Aditya21neve** [comment]
Download, Features and team page added with navigation bar

**Comment by Deadshot0x7** [comment]
team
 
Everything is good by what happened to the  Team.html?

**Review by Deadshot0x7 — COMMENTED** [review]
Everything is good

**Pull request merged**
